apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
configMapGenerator:
  - name: logagg-config
    behavior: merge
    literals:
      - LOG_LEVEL=info
      - NATS_BACKPRESSURE_STRATEGY=reject
      - NATS_QUEUE_LAG_HIGH_WATERMARK=25000
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
