apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: logagg
resources:
  - namespace.yaml
  - service-account.yaml
  - configmap.yaml
  - ingest-api.yaml
  - processor.yaml
  - query-api.yaml
  - network-policy.yaml
images:
  - name: logagg/ingest-api
    newTag: latest
  - name: logagg/processor
    newTag: latest
  - name: logagg/query-api
    newTag: latest
